import './PrivacyP.css'
function PrivacyP(){
    return(
    <>

    <div className='PrivacyP-mainContent'>
    <div className='PrivacyP-middleContent'>

        <h1>PRIVACY POLICY</h1>
        <p>We, 3 Dots Design Pvt. Ltd.. (“3 Dots Design Pvt. Ltd.”, “We”, “us”, “our”) are the owners of the website www.3dotsdesign.in (“Website”). We offer a wide range of advertisement services related to digital marketing, digital content generation, print media advertisements. We assist our customers meet their requirements related to product branding, designing and various other promotional activities (“Services”).</p>

        <p>We respect data privacy rights and are committed to protecting personal information collected on the Website. This privacy policy (“Privacy Policy”) sets forth how we collect, use and protect the personal information collected on the Website.</p>

        <h1>1. WHAT DATA DO WE COLLECT?</h1>
        <p>To get in touch with us through the enquiry form available in the ‘contact us’ section or to apply for a job through the ‘careers’ section on the Website, you are required to provide us with your information including but not limited to your first name, last name, e-mail address, contact number and resume details. For the sake of brevity, the aforementioned information shall be referred to as “Personal Information”.</p>

        <p>We also collect certain non-personal information on the way you use our Website, through tools such as Google Analytics (a brief description of the same is provided below). This is done primarily to enhance user experience. These tools collect certain information which helps us understand how many visitors have visited the Website and also, their behaviour.</p>

        <p><b>Google Analytics-</b> This website uses Google Analytics, a web analytics service provided by Google Inc. (“Google”). Google Analytics uses cookies, text files that are stored on your computer and enable analysis of your use of the Website. The information generated by the cookies about your use of this Website are usually transferred to a server of Google in the US and stored there. In case of activation of IP anonymization on this Website your IP address from Google will be truncated within Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases is the full IP address is transmitted to a Google server in the US and shortened there. You can refuse the use of cookies by selecting the appropriate settings on your browser software. You can also prevent the data generated by the cookie and related to your use of the website to Google and the processing of these data by Google, by selecting the in the following link (https (including your IP address.): // Download tools.google.com/dlpage/gaoptout/) available browser plug-in and install it.</p>

        <p><b>Adwords:</b> We use Google Adwords as a marketing tool to allow the members of the public to reach out to us through our Website. We also collect and store information when you, in order to interact with us, click on our advertisement which is displayed on Google search page and subsequently get directed to our Website.</p>

        <p><b>Website and Social media accounts-</b>We may also collect, store and use your Personal Information when you (1) access or provide your Personal Information on our social networking handles operated by us on Facebook, Twitter, and/or LinkedIn (2) share our blogs through Facebook, Twitter, and/or LinkedIn and (3) comment/ provide feedback/testimonials on such social networking handles</p>

        <p><b>Cookies-</b> We use cookies and similar tracking technologies to track user traffic patterns and hold certain registration information. Tracking technologies also used are beacons, tags and scripts to collect and track information and to improve and analyze our service. If you wish to not have the information these technologies collect, used for the purpose of serving you targeted ads the Help menu on the menu bar of most browsers will tell you how to prevent your browser from accepting new cookies, how to disable cookies altogether etc.</p>

        <p><b>We use cookies to:</b><br />
improve the user experience on the website <br />
understand the usage based on the geographical area <br />
understand the usage based on the demographics <br />
understand and get usage patterns of the users <br />
Examples of Cookies We Use: Session cookies, First party cookies, Third Party cookies, Secure Cookies, HTTP-only cookies, Flash cookies, Zombie cookies.</p>

<p><b>The cookies will collect following information:</b><br />
Clicks and scroll on the Website; <br />
Visitor’s operating system, browser information, CPU, GPU; and Information of Service Provider. <br />
Will disabling the cookies allow users to use the Website?<br />
We will not restrict the usage of the Website if the cookies are disabled.</p>

<p>Accuracy of information. Please make sure that any Personal Information you share with us is accurate and up to date information. If you are sharing any Personal Information on behalf of a third person, you should ensure that you are authorized to do so.</p>
    </div>
    </div>
    
    </>
    )
}
export default PrivacyP;